import { SkillCategory } from "@utils/types";
import { FaLaptopCode, FaTools } from "react-icons/fa";

export const skillCategories: SkillCategory[] = [
  {
    categoryTranslationKey: "section.skills.programming",
    categoryIcon: FaLaptopCode,
    skills: [
      {
        name: "Java",
        knowledgePercentage: 90,
        skillColor: "red",
        informationType: "tags",
        tags: [
          "Spring",
          "Spring Boot",
          "Hibernate",
          "Maven",
          "RxJava",
          "Lombok",
          "MapStruct",
          "Swagger",
          "JavaFX",
          "JUnit",
          "Future API",
          "Stream API",
        ],
      },
      {
        name: "JavaScript",
        knowledgePercentage: 80,
        skillColor: "yellow",
        informationType: "tags",
        tags: [
          "React",
          "Chakra UI",
          "Material UI",
          "framer-motion",
          "d3",
          "i18n",
          "three.js",
          "axios",
          "jquery",
          "RxJs",
          "Promise API",
          "npm",
          "eslint",
        ],
      },
      {
        name: "Python",
        knowledgePercentage: 75,
        skillColor: "cyan",
        informationType: "tags",
        tags: ["numpy", "pandas", "openCV", "scikit-learn", "pip", "venv"],
      },
      {
        name: "C#",
        knowledgePercentage: 60,
        skillColor: "purple",
        informationType: "tags",
        tags: ["Task API", "LINQ", "WPF"],
      },
      {
        name: "C++",
        knowledgePercentage: 55,
        skillColor: "blue",
        informationType: "tags",
        tags: ["openCV", "GoogleTest"],
      },
    ],
  },
  {
    categoryTranslationKey: "section.skills.tools",
    categoryIcon: FaTools,
    skills: [
      {
        name: "VS Code",
        knowledgePercentage: 100,
        skillColor: "blue",
        informationType: "text",
        textTranslationKey: "section.skills.vsCode",
      },
      {
        name: "Intellij IDEA",
        knowledgePercentage: 100,
        skillColor: "red",
        informationType: "text",
        textTranslationKey: "section.skills.intellij",
      },
      {
        name: "Git",
        knowledgePercentage: 90,
        skillColor: "red",
        informationType: "text",
        textTranslationKey: "section.skills.git",
      },
      {
        name: "Visual Studio",
        knowledgePercentage: 80,
        skillColor: "purple",
        informationType: "text",
        textTranslationKey: "section.skills.visualStudio",
      },
      {
        name: "Linux",
        knowledgePercentage: 70,
        skillColor: "orange",
        informationType: "text",
        textTranslationKey: "section.skills.linux",
      },
      {
        name: "Postgres",
        knowledgePercentage: 70,
        skillColor: "blue",
        informationType: "text",
        textTranslationKey: "section.skills.postgres",
      },
      {
        name: "Atlassian",
        knowledgePercentage: 70,
        skillColor: "cyan",
        informationType: "text",
        textTranslationKey: "section.skills.atlassian",
      },
      {
        name: "Liquibase",
        knowledgePercentage: 55,
        skillColor: "red",
        informationType: "text",
        textTranslationKey: "section.skills.liquibase",
      },
      {
        name: "Docker",
        knowledgePercentage: 50,
        skillColor: "blue",
        informationType: "text",
        textTranslationKey: "section.skills.docker",
      },
      {
        name: "CMake",
        knowledgePercentage: 40,
        skillColor: "green",
        informationType: "text",
        textTranslationKey: "section.skills.cmake",
      },
    ],
  },
];
